package infrastructure

import (
	"github.com/abekoh/mapc/examples/sqlc-domainmodel/domain"
	"github.com/abekoh/mapc/examples/sqlc-domainmodel/infrastructure/sqlc"
)

// MapUserToUser maps User to User.
// This function is generated by mapc.
// DO NOT EDIT this function.
func MapUserToUser(x sqlc.User) domain.User {
	return domain.User{
		ID:   domain.UserID(x.ID),
		Name: x.Name,
	}
}

// MapTaskToTask maps Task to Task.
// This function is generated by mapc.
// DO NOT EDIT this function.
func MapTaskToTask(x sqlc.Task) domain.Task {
	return domain.Task{
		ID:           domain.TaskID(x.ID),
		UserID:       domain.UserID(x.UserID),
		Title:        x.Title,
		Description:  x.Description,
		RegisteredAt: x.RegisteredAt,
		// StoryPoint:
	}
}

// MapSubTaskToSubTask maps SubTask to SubTask.
// This function is generated by mapc.
// DO NOT EDIT this function.
func MapSubTaskToSubTask(x sqlc.SubTask) domain.SubTask {
	return domain.SubTask{
		ID:           domain.SubTaskID(x.ID),
		TaskID:       domain.TaskID(x.TaskID),
		UserID:       domain.UserID(x.UserID),
		Title:        x.Title,
		Description:  x.Description,
		RegisteredAt: x.RegisteredAt,
	}
}
