package graphql

import (
	"github.com/abekoh/mapc/example/graphql/gqlmodel"
	"github.com/abekoh/mapc/example/infrastructure/sqlc"
)

// MapUserToUser maps User to User.
// This function is generated by mapc.
// DO NOT EDIT this function.
func MapUserToUser(x sqlc.User) gqlmodel.User {
	return gqlmodel.User{
		ID:   x.ID,
		Name: x.Name,
	}
}

// MapTaskToTask maps Task to Task.
// This function is generated by mapc.
// DO NOT EDIT this function.
func MapTaskToTask(x sqlc.Task) gqlmodel.Task {
	return gqlmodel.Task{
		ID:           x.ID,
		Title:        x.Title,
		Description:  x.Description,
		RegisteredAt: x.RegisteredAt,
		// StoryPoint:
		// User:
		// SubTasks:
	}
}

// MapSubTaskToSubTask maps SubTask to SubTask.
// This function is generated by mapc.
// DO NOT EDIT this function.
func MapSubTaskToSubTask(x sqlc.SubTask) gqlmodel.SubTask {
	return gqlmodel.SubTask{
		ID:           x.ID,
		Title:        x.Title,
		Description:  x.Description,
		RegisteredAt: x.RegisteredAt,
		// StoryPoint:
		// User:
	}
}
