package graph

import (
	"github.com/abekoh/mapc/example/graph/model"
	"github.com/abekoh/mapc/example/infrastructure/sqlc"
)

// MapUserToUser maps User to User.
// This function is generated by mapc.
// DO NOT EDIT this function.
func MapUserToUser(x sqlc.User) model.User {
	return model.User{
		ID:   x.ID,
		Name: x.Name,
	}
}

// MapTaskToTask maps Task to Task.
// This function is generated by mapc.
// DO NOT EDIT this function.
func MapTaskToTask(x sqlc.Task) model.Task {
	return model.Task{
		ID:           x.ID,
		Title:        x.Title,
		Description:  x.Description,
		RegisteredAt: x.RegisteredAt,
		// StoryPoint:
		// User:
		// SubTasks:
	}
}

// MapSubTaskToSubTask maps SubTask to SubTask.
// This function is generated by mapc.
// DO NOT EDIT this function.
func MapSubTaskToSubTask(x sqlc.SubTask) model.SubTask {
	return model.SubTask{
		ID:           x.ID,
		Title:        x.Title,
		Description:  x.Description,
		RegisteredAt: x.RegisteredAt,
		// StoryPoint:
		// User:
	}
}
