package infrastructure

import (
	"github.com/abekoh/mapc/examples/sqlc-domainmodel/domain"
	"github.com/abekoh/mapc/examples/sqlc-domainmodel/infrastructure/sqlc"
)

// MapUserToUser maps User to User.
// This function is generated by mapc.
// You can edit mapping fields.
func MapUserToUser(x sqlc.User) domain.User {
	return domain.User{
		Name: x.Name,
		ID:   "hoge",
	}
}

// MapTaskToTask maps Task to Task.
// This function is generated by mapc.
// You can edit mapping fields.
func MapTaskToTask(x sqlc.Task) domain.Task {
	return domain.Task{
		Title:        x.Title,
		Description:  x.Description,
		RegisteredAt: x.RegisteredAt,
		// ID:
		// UserID:
		// StoryPoint:
	}
}

// MapSubTaskToSubTask maps SubTask to SubTask.
// This function is generated by mapc.
// You can edit mapping fields.
func MapSubTaskToSubTask(x sqlc.SubTask) domain.SubTask {
	return domain.SubTask{
		Title:        x.Title,
		Description:  x.Description,
		RegisteredAt: x.RegisteredAt,
		// ID:
		// TaskID:
		// UserID:
	}
}
