package infrastructure

import (
	"github.com/abekoh/mapc/examples/sqlc-domainmodel/domain"
	"github.com/abekoh/mapc/examples/sqlc-domainmodel/infrastructure/sqlc"
)

// MapUserToUser maps User to User.
// This function is generated by mapc.
// You can edit mapping fields.
func MapUserToUser(x sqlc.User) domain.User {
	return domain.User{
		Name: x.Name,
		// ID:
	}
}
