// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodel

import (
	"time"
)

type NewUser struct {
	Name string `json:"name"`
}

type SubTask struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	StoryPoint   *int      `json:"storyPoint"`
	RegisteredAt time.Time `json:"registeredAt"`
	User         *User     `json:"user"`
}

type Task struct {
	ID           string     `json:"id"`
	Title        string     `json:"title"`
	Description  string     `json:"description"`
	StoryPoint   *int       `json:"storyPoint"`
	RegisteredAt time.Time  `json:"registeredAt"`
	User         *User      `json:"user"`
	SubTasks     []*SubTask `json:"subTasks"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
